// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.29.3
// source: message.proto

package message

import (
	common "./common"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Strike_Signup_FullMethodName          = "/message.Strike/Signup"
	Strike_Login_FullMethodName           = "/message.Strike/Login"
	Strike_SaltMine_FullMethodName        = "/message.Strike/SaltMine"
	Strike_UserRequest_FullMethodName     = "/message.Strike/UserRequest"
	Strike_OnlineUsers_FullMethodName     = "/message.Strike/OnlineUsers"
	Strike_StatusStream_FullMethodName    = "/message.Strike/StatusStream"
	Strike_SendPayload_FullMethodName     = "/message.Strike/SendPayload"
	Strike_PayloadStream_FullMethodName   = "/message.Strike/PayloadStream"
	Strike_PollServer_FullMethodName      = "/message.Strike/PollServer"
	Strike_DeliveryReceipt_FullMethodName = "/message.Strike/DeliveryReceipt"
)

// StrikeClient is the client API for Strike service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StrikeClient interface {
	// TODO: Just login?
	Signup(ctx context.Context, in *InitUser, opts ...grpc.CallOption) (*ServerResponse, error)
	Login(ctx context.Context, in *LoginVerify, opts ...grpc.CallOption) (*ServerResponse, error)
	SaltMine(ctx context.Context, in *common.UserInfo, opts ...grpc.CallOption) (*Salt, error)
	UserRequest(ctx context.Context, in *common.UserInfo, opts ...grpc.CallOption) (*common.UserInfo, error)
	OnlineUsers(ctx context.Context, in *common.UserInfo, opts ...grpc.CallOption) (*Users, error)
	StatusStream(ctx context.Context, in *common.UserInfo, opts ...grpc.CallOption) (Strike_StatusStreamClient, error)
	SendPayload(ctx context.Context, in *StreamPayload, opts ...grpc.CallOption) (*ServerResponse, error)
	PayloadStream(ctx context.Context, in *common.UserInfo, opts ...grpc.CallOption) (Strike_PayloadStreamClient, error)
	PollServer(ctx context.Context, in *common.UserInfo, opts ...grpc.CallOption) (*ServerInfo, error)
	DeliveryReceipt(ctx context.Context, in *Receipt, opts ...grpc.CallOption) (*ServerResponse, error)
}

type strikeClient struct {
	cc grpc.ClientConnInterface
}

func NewStrikeClient(cc grpc.ClientConnInterface) StrikeClient {
	return &strikeClient{cc}
}

func (c *strikeClient) Signup(ctx context.Context, in *InitUser, opts ...grpc.CallOption) (*ServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerResponse)
	err := c.cc.Invoke(ctx, Strike_Signup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strikeClient) Login(ctx context.Context, in *LoginVerify, opts ...grpc.CallOption) (*ServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerResponse)
	err := c.cc.Invoke(ctx, Strike_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strikeClient) SaltMine(ctx context.Context, in *common.UserInfo, opts ...grpc.CallOption) (*Salt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Salt)
	err := c.cc.Invoke(ctx, Strike_SaltMine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strikeClient) UserRequest(ctx context.Context, in *common.UserInfo, opts ...grpc.CallOption) (*common.UserInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.UserInfo)
	err := c.cc.Invoke(ctx, Strike_UserRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strikeClient) OnlineUsers(ctx context.Context, in *common.UserInfo, opts ...grpc.CallOption) (*Users, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Users)
	err := c.cc.Invoke(ctx, Strike_OnlineUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strikeClient) StatusStream(ctx context.Context, in *common.UserInfo, opts ...grpc.CallOption) (Strike_StatusStreamClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Strike_ServiceDesc.Streams[0], Strike_StatusStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &strikeStatusStreamClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Strike_StatusStreamClient interface {
	Recv() (*StatusUpdate, error)
	grpc.ClientStream
}

type strikeStatusStreamClient struct {
	grpc.ClientStream
}

func (x *strikeStatusStreamClient) Recv() (*StatusUpdate, error) {
	m := new(StatusUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *strikeClient) SendPayload(ctx context.Context, in *StreamPayload, opts ...grpc.CallOption) (*ServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerResponse)
	err := c.cc.Invoke(ctx, Strike_SendPayload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strikeClient) PayloadStream(ctx context.Context, in *common.UserInfo, opts ...grpc.CallOption) (Strike_PayloadStreamClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Strike_ServiceDesc.Streams[1], Strike_PayloadStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &strikePayloadStreamClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Strike_PayloadStreamClient interface {
	Recv() (*StreamPayload, error)
	grpc.ClientStream
}

type strikePayloadStreamClient struct {
	grpc.ClientStream
}

func (x *strikePayloadStreamClient) Recv() (*StreamPayload, error) {
	m := new(StreamPayload)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *strikeClient) PollServer(ctx context.Context, in *common.UserInfo, opts ...grpc.CallOption) (*ServerInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerInfo)
	err := c.cc.Invoke(ctx, Strike_PollServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strikeClient) DeliveryReceipt(ctx context.Context, in *Receipt, opts ...grpc.CallOption) (*ServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerResponse)
	err := c.cc.Invoke(ctx, Strike_DeliveryReceipt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StrikeServer is the server API for Strike service.
// All implementations must embed UnimplementedStrikeServer
// for forward compatibility
type StrikeServer interface {
	// TODO: Just login?
	Signup(context.Context, *InitUser) (*ServerResponse, error)
	Login(context.Context, *LoginVerify) (*ServerResponse, error)
	SaltMine(context.Context, *common.UserInfo) (*Salt, error)
	UserRequest(context.Context, *common.UserInfo) (*common.UserInfo, error)
	OnlineUsers(context.Context, *common.UserInfo) (*Users, error)
	StatusStream(*common.UserInfo, Strike_StatusStreamServer) error
	SendPayload(context.Context, *StreamPayload) (*ServerResponse, error)
	PayloadStream(*common.UserInfo, Strike_PayloadStreamServer) error
	PollServer(context.Context, *common.UserInfo) (*ServerInfo, error)
	DeliveryReceipt(context.Context, *Receipt) (*ServerResponse, error)
	mustEmbedUnimplementedStrikeServer()
}

// UnimplementedStrikeServer must be embedded to have forward compatible implementations.
type UnimplementedStrikeServer struct {
}

func (UnimplementedStrikeServer) Signup(context.Context, *InitUser) (*ServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (UnimplementedStrikeServer) Login(context.Context, *LoginVerify) (*ServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedStrikeServer) SaltMine(context.Context, *common.UserInfo) (*Salt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaltMine not implemented")
}
func (UnimplementedStrikeServer) UserRequest(context.Context, *common.UserInfo) (*common.UserInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRequest not implemented")
}
func (UnimplementedStrikeServer) OnlineUsers(context.Context, *common.UserInfo) (*Users, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnlineUsers not implemented")
}
func (UnimplementedStrikeServer) StatusStream(*common.UserInfo, Strike_StatusStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method StatusStream not implemented")
}
func (UnimplementedStrikeServer) SendPayload(context.Context, *StreamPayload) (*ServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPayload not implemented")
}
func (UnimplementedStrikeServer) PayloadStream(*common.UserInfo, Strike_PayloadStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method PayloadStream not implemented")
}
func (UnimplementedStrikeServer) PollServer(context.Context, *common.UserInfo) (*ServerInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PollServer not implemented")
}
func (UnimplementedStrikeServer) DeliveryReceipt(context.Context, *Receipt) (*ServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeliveryReceipt not implemented")
}
func (UnimplementedStrikeServer) mustEmbedUnimplementedStrikeServer() {}

// UnsafeStrikeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StrikeServer will
// result in compilation errors.
type UnsafeStrikeServer interface {
	mustEmbedUnimplementedStrikeServer()
}

func RegisterStrikeServer(s grpc.ServiceRegistrar, srv StrikeServer) {
	s.RegisterService(&Strike_ServiceDesc, srv)
}

func _Strike_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrikeServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strike_Signup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrikeServer).Signup(ctx, req.(*InitUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strike_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginVerify)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrikeServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strike_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrikeServer).Login(ctx, req.(*LoginVerify))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strike_SaltMine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.UserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrikeServer).SaltMine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strike_SaltMine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrikeServer).SaltMine(ctx, req.(*common.UserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strike_UserRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.UserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrikeServer).UserRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strike_UserRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrikeServer).UserRequest(ctx, req.(*common.UserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strike_OnlineUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.UserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrikeServer).OnlineUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strike_OnlineUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrikeServer).OnlineUsers(ctx, req.(*common.UserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strike_StatusStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(common.UserInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StrikeServer).StatusStream(m, &strikeStatusStreamServer{ServerStream: stream})
}

type Strike_StatusStreamServer interface {
	Send(*StatusUpdate) error
	grpc.ServerStream
}

type strikeStatusStreamServer struct {
	grpc.ServerStream
}

func (x *strikeStatusStreamServer) Send(m *StatusUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func _Strike_SendPayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrikeServer).SendPayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strike_SendPayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrikeServer).SendPayload(ctx, req.(*StreamPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strike_PayloadStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(common.UserInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StrikeServer).PayloadStream(m, &strikePayloadStreamServer{ServerStream: stream})
}

type Strike_PayloadStreamServer interface {
	Send(*StreamPayload) error
	grpc.ServerStream
}

type strikePayloadStreamServer struct {
	grpc.ServerStream
}

func (x *strikePayloadStreamServer) Send(m *StreamPayload) error {
	return x.ServerStream.SendMsg(m)
}

func _Strike_PollServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.UserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrikeServer).PollServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strike_PollServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrikeServer).PollServer(ctx, req.(*common.UserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strike_DeliveryReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Receipt)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrikeServer).DeliveryReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strike_DeliveryReceipt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrikeServer).DeliveryReceipt(ctx, req.(*Receipt))
	}
	return interceptor(ctx, in, info, handler)
}

// Strike_ServiceDesc is the grpc.ServiceDesc for Strike service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Strike_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.Strike",
	HandlerType: (*StrikeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signup",
			Handler:    _Strike_Signup_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Strike_Login_Handler,
		},
		{
			MethodName: "SaltMine",
			Handler:    _Strike_SaltMine_Handler,
		},
		{
			MethodName: "UserRequest",
			Handler:    _Strike_UserRequest_Handler,
		},
		{
			MethodName: "OnlineUsers",
			Handler:    _Strike_OnlineUsers_Handler,
		},
		{
			MethodName: "SendPayload",
			Handler:    _Strike_SendPayload_Handler,
		},
		{
			MethodName: "PollServer",
			Handler:    _Strike_PollServer_Handler,
		},
		{
			MethodName: "DeliveryReceipt",
			Handler:    _Strike_DeliveryReceipt_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StatusStream",
			Handler:       _Strike_StatusStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PayloadStream",
			Handler:       _Strike_PayloadStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "message.proto",
}
