// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.29.3
// source: federation.proto

package federation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Federation_Ping_FullMethodName         = "/federation.Federation/Ping"
	Federation_RoutePayload_FullMethodName = "/federation.Federation/RoutePayload"
	Federation_Ack_FullMethodName          = "/federation.Federation/Ack"
	Federation_Presence_FullMethodName     = "/federation.Federation/Presence"
)

// FederationClient is the client API for Federation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FederationClient interface {
	Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*FedAck, error)
	RoutePayload(ctx context.Context, in *FedPayload, opts ...grpc.CallOption) (*FedAck, error)
	Ack(ctx context.Context, in *FedAck, opts ...grpc.CallOption) (*AckResponse, error)
	Presence(ctx context.Context, in *Status, opts ...grpc.CallOption) (Federation_PresenceClient, error)
}

type federationClient struct {
	cc grpc.ClientConnInterface
}

func NewFederationClient(cc grpc.ClientConnInterface) FederationClient {
	return &federationClient{cc}
}

func (c *federationClient) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*FedAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FedAck)
	err := c.cc.Invoke(ctx, Federation_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationClient) RoutePayload(ctx context.Context, in *FedPayload, opts ...grpc.CallOption) (*FedAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FedAck)
	err := c.cc.Invoke(ctx, Federation_RoutePayload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationClient) Ack(ctx context.Context, in *FedAck, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, Federation_Ack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationClient) Presence(ctx context.Context, in *Status, opts ...grpc.CallOption) (Federation_PresenceClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Federation_ServiceDesc.Streams[0], Federation_Presence_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &federationPresenceClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Federation_PresenceClient interface {
	Recv() (*FedAck, error)
	grpc.ClientStream
}

type federationPresenceClient struct {
	grpc.ClientStream
}

func (x *federationPresenceClient) Recv() (*FedAck, error) {
	m := new(FedAck)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FederationServer is the server API for Federation service.
// All implementations must embed UnimplementedFederationServer
// for forward compatibility
type FederationServer interface {
	Ping(context.Context, *PingReq) (*FedAck, error)
	RoutePayload(context.Context, *FedPayload) (*FedAck, error)
	Ack(context.Context, *FedAck) (*AckResponse, error)
	Presence(*Status, Federation_PresenceServer) error
	mustEmbedUnimplementedFederationServer()
}

// UnimplementedFederationServer must be embedded to have forward compatible implementations.
type UnimplementedFederationServer struct {
}

func (UnimplementedFederationServer) Ping(context.Context, *PingReq) (*FedAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedFederationServer) RoutePayload(context.Context, *FedPayload) (*FedAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RoutePayload not implemented")
}
func (UnimplementedFederationServer) Ack(context.Context, *FedAck) (*AckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ack not implemented")
}
func (UnimplementedFederationServer) Presence(*Status, Federation_PresenceServer) error {
	return status.Errorf(codes.Unimplemented, "method Presence not implemented")
}
func (UnimplementedFederationServer) mustEmbedUnimplementedFederationServer() {}

// UnsafeFederationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FederationServer will
// result in compilation errors.
type UnsafeFederationServer interface {
	mustEmbedUnimplementedFederationServer()
}

func RegisterFederationServer(s grpc.ServiceRegistrar, srv FederationServer) {
	s.RegisterService(&Federation_ServiceDesc, srv)
}

func _Federation_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Federation_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServer).Ping(ctx, req.(*PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Federation_RoutePayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FedPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServer).RoutePayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Federation_RoutePayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServer).RoutePayload(ctx, req.(*FedPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _Federation_Ack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FedAck)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServer).Ack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Federation_Ack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServer).Ack(ctx, req.(*FedAck))
	}
	return interceptor(ctx, in, info, handler)
}

func _Federation_Presence_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Status)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FederationServer).Presence(m, &federationPresenceServer{ServerStream: stream})
}

type Federation_PresenceServer interface {
	Send(*FedAck) error
	grpc.ServerStream
}

type federationPresenceServer struct {
	grpc.ServerStream
}

func (x *federationPresenceServer) Send(m *FedAck) error {
	return x.ServerStream.SendMsg(m)
}

// Federation_ServiceDesc is the grpc.ServiceDesc for Federation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Federation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "federation.Federation",
	HandlerType: (*FederationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Federation_Ping_Handler,
		},
		{
			MethodName: "RoutePayload",
			Handler:    _Federation_RoutePayload_Handler,
		},
		{
			MethodName: "Ack",
			Handler:    _Federation_Ack_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Presence",
			Handler:       _Federation_Presence_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "federation.proto",
}
