peers:
  - id: "a647a94b2b9ec25cc159a944ba964455"
    name: "endpoint0"
    addr: "strike-server1:9090"
    pubkey: "MCowBQYDK2VwAyEAb4h1y68b4fYvXQ50ickpnLZANMN22OKZgvhwgP+jbnA="
  - id: "4949181be9c55ac37a04048b93d6fc09"
    name: "endpoint1"
    addr: "strike-server2:9090"
    pubkey: "MCowBQYDK2VwAyEAQzcFv4Uq9W0JyudOfqnbvpGju9rgjvtyUFGrlpDgQ/k="
