apiVersion: apps/v1
kind: Deployment
metadata:
  name: strike-db
  labels:
    app: strike-db
spec:
  selector:
    matchLabels:
      app: strike-db
  template:
    metadata:
      labels:
        app: strike-db
    spec:
      containers:
      - name: strike-db
        image: strike_db 
        ports:
        - containerPort: 5432
