apiVersion: apps/v1
kind: Deployment
metadata:
  name: strike-server
  namespace: strike
  labels:
    app: strike-server
spec:
  selector:
    matchLabels:
      app: strike-server
  template:
    metadata:
      labels:
        app: strike-server
    spec:
      containers:
      - name: strike-server
        image: strike_server
        ports:
        - containerPort: 8080
        envFrom:
            - secretRef:
                name: strike-server-env
            - secretRef:
                name: strike-server-identity
